# -*- coding: utf-8 -*-
"""pdf_summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srrrtULNKUExaWBNe-dt6yY0x95ne78-
"""

# Commented out IPython magic to ensure Python compatibility.

# ---------- 1. 설치 ----------
from google.colab import drive
drive.mount('/content/drive')

!mkdir /content/drive/MyDrive/hci
# %cd /content/drive/MyDrive/hci

!pip install pdfplumber transformers sentencepiece -q

# ---------- 2. import ----------
import os
import requests
import pandas as pd
import pdfplumber
from transformers import pipeline

# ---------- 3. 요약 모델 준비 ----------
# 영어/다국어 기본 모델 (속도/용량 생각해서 작은 걸로)
# 한국어 전용 모델 쓰고 싶으면 model_name만 나중에 바꾸면 됨.
model_name = "t5-small"

summarizer = pipeline(
    "summarization",
    model=model_name,
    tokenizer=model_name
)


# ---------- 4. PDF 다운로드 ----------
def download_pdf(url, save_dir="pdf_tmp", filename=None):
    """
    url에서 pdf를 받아서 save_dir/filename 에 저장하고, 경로를 반환
    """
    os.makedirs(save_dir, exist_ok=True)

    if filename is None:
        # 파일명 없으면 간단하게 해시처럼 숫자만 줌
        filename = "temp.pdf"
    pdf_path = os.path.join(save_dir, filename)

    try:
        resp = requests.get(url, timeout=15)
        resp.raise_for_status()
    except Exception as e:
        print(f"[다운로드 실패] {url} -> {e}")
        return None

    with open(pdf_path, "wb") as f:
        f.write(resp.content)

    return pdf_path



# ---------- 5. pdfplumber로 텍스트 추출 ----------
def extract_text(pdf_path):
    """
    pdfplumber로 PDF 전체 텍스트 추출
    """
    if pdf_path is None or not os.path.exists(pdf_path):
        return ""

    text = ""
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                t = page.extract_text()
                if t:
                    text += t + "\n"
    except Exception as e:
        print(f"[텍스트 추출 실패] {pdf_path} -> {e}")
        return ""

    return text


# ---------- 6. 긴 텍스트 요약 ----------
def summarize_text(text, max_chunk_chars=1500, max_len=200, min_len=40):
    """
    텍스트가 너무 길면 잘라서 여러 번 요약한 뒤,
    그 요약들을 다시 한 번 요약해서 최종 요약 생성.
    (대충 돌아가게 만든 버전)
    """
    if not text or len(text.strip()) == 0:
        return ""

    # 1) 길면 chunk로 나누기
    chunks = []
    t = text.strip()
    while len(t) > 0:
        chunks.append(t[:max_chunk_chars])
        t = t[max_chunk_chars:]

    partial_summaries = []
    for c in chunks:
        try:
            out = summarizer(
                c,
                max_length=max_len,
                min_length=min_len,
                do_sample=False
            )
            partial_summaries.append(out[0]["summary_text"])
        except Exception as e:
            print(f"[부분 요약 실패] {e}")

    if not partial_summaries:
        return ""

    # 2) 부분 요약들 다시 합쳐서 한 번 더 요약
    joined = " ".join(partial_summaries)
    try:
        final = summarizer(
            joined,
            max_length=max_len,
            min_length=min_len,
            do_sample=False
        )
        return final[0]["summary_text"]
    except Exception as e:
        print(f"[최종 요약 실패] {e}")
        return joined  # 실패하면 부분 요약들 그대로 반환


# ---------- 7. CSV 읽기 ----------
csv_path = "/content/drive/MyDrive/hci/리포트_데이터.csv"   # 업로드한 파일 이름
df = pd.read_csv(csv_path)

print("컬럼 목록:", df.columns.tolist())
print("행 개수:", len(df))


# ---------- 8. 요약 컬럼 준비 ----------
summary_col = "내용요약"

if summary_col not in df.columns:
    df[summary_col] = ""   # 새 컬럼 생성


# ---------- 9. 행별로 PDF 요약 붙이기 ----------

url_col = "첨부파일"   # CSV에서 PDF 링크가 들어있는 컬럼 이름

for idx, row in df.iterrows():
    url = row.get(url_col, "")

    # 이미 요약이 있으면 스킵 (다시 돌릴 때 중복 방지용)
    already = str(row.get(summary_col, "")).strip()
    if already:
        continue

    if not isinstance(url, str) or not url.startswith("http"):
        print(f"[스킵] idx={idx} 잘못된 URL: {url}")
        continue

    print(f"\n[진행] idx={idx}, 종목명={row.get('종목명', '')}, URL={url[:60]}...")

    # 1) PDF 다운로드
    pdf_filename = f"report_{idx}.pdf"
    pdf_path = download_pdf(url, filename=pdf_filename)
    if pdf_path is None:
        continue

    # 2) 텍스트 추출
    text = extract_text(pdf_path)
    if len(text.strip()) == 0:
        print(f"[경고] 텍스트 없음 idx={idx}")
        continue

    # 3) 요약
    summary = summarize_text(text)
    print(f"[요약 완료] 길이={len(summary)}")

    # 4) CSV에 저장
    df.loc[idx, summary_col] = summary


# ---------- 10. 결과 저장 ----------
output_path = "리포트_데이터_요약추가.csv"
df.to_csv(output_path, index=False)
print("저장 완료:", output_path)